package com.virtual7.businessComponents.model.client;

import com.virtual7.businessComponents.model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 15 13:06:28 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void varSalary() {
        Object _ret = this.riInvokeExportedMethod(this,"varSalary",null,null);
        return;
    }

    public void varLName() {
        Object _ret = this.riInvokeExportedMethod(this,"varLName",null,null);
        return;
    }

    public void varFName() {
        Object _ret = this.riInvokeExportedMethod(this,"varFName",null,null);
        return;
    }

    public void varEmail() {
        Object _ret = this.riInvokeExportedMethod(this,"varEmail",null,null);
        return;
    }

    public void removeWhereClauseParam() {
        Object _ret = this.riInvokeExportedMethod(this,"removeWhereClauseParam",null,null);
        return;
    }
}
