package com.virtual7.updateForHistorysation.model;

import com.virtual7.updateForHistorysation.model.common.AppModule;
import com.virtual7.updateForHistorysation.model.views.DepartmentsVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 24 17:17:44 EEST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsVO.
     * @return DepartmentsVO
     */
    public DepartmentsVOImpl getDepartmentsVO() {
        return (DepartmentsVOImpl)findViewObject("DepartmentsVO");
    }
    
    public void clearEntityCache() {
        this.getTransaction().clearEntityCache("com.virtual7.updateForHistorization.Departments");
    }
}
