package com.virtual7.bcCaching.model.client;

import com.virtual7.bcCaching.model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 16:06:01 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void updateDepartmentNewJDBC() {
        Object _ret = this.riInvokeExportedMethod(this,"updateDepartmentNewJDBC",null,null);
        return;
    }

    public void updateDepartment() {
        Object _ret = this.riInvokeExportedMethod(this,"updateDepartment",null,null);
        return;
    }

    public void readAndPrintDepartmentService() {
        Object _ret = this.riInvokeExportedMethod(this,"readAndPrintDepartmentService",null,null);
        return;
    }

    public void readAndPrintDepartmentNewJDBC() {
        Object _ret = this.riInvokeExportedMethod(this,"readAndPrintDepartmentNewJDBC",null,null);
        return;
    }

    public void readAndPrintDepartment() {
        Object _ret = this.riInvokeExportedMethod(this,"readAndPrintDepartment",null,null);
        return;
    }

    public void insertNewDepartmentNewJDBC() {
        Object _ret = this.riInvokeExportedMethod(this,"insertNewDepartmentNewJDBC",null,null);
        return;
    }

    public void insertNewDepartment() {
        Object _ret = this.riInvokeExportedMethod(this,"insertNewDepartment",null,null);
        return;
    }

    public void executeServiceQueryVL() {
        Object _ret = this.riInvokeExportedMethod(this,"executeServiceQueryVL",null,null);
        return;
    }

    public void executeServiceQueryEL() {
        Object _ret = this.riInvokeExportedMethod(this,"executeServiceQueryEL",null,null);
        return;
    }

    public void executeServiceQuery() {
        Object _ret = this.riInvokeExportedMethod(this,"executeServiceQuery",null,null);
        return;
    }

    public void executeQuery6() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery6",null,null);
        return;
    }

    public void executeQuery5() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery5",null,null);
        return;
    }

    public void executeQuery4() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery4",null,null);
        return;
    }

    public void executeQuery3() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery3",null,null);
        return;
    }

    public void executeQuery2() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery2",null,null);
        return;
    }

    public void executeQuery1() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery1",null,null);
        return;
    }

    public void executeQuery() {
        Object _ret = this.riInvokeExportedMethod(this,"executeQuery",null,null);
        return;
    }

    public void deleteDepartmentNewJDBC() {
        Object _ret = this.riInvokeExportedMethod(this,"deleteDepartmentNewJDBC",null,null);
        return;
    }

    public void deleteDepartment() {
        Object _ret = this.riInvokeExportedMethod(this,"deleteDepartment",null,null);
        return;
    }

    public void vo_printCurrentVOQueryMode() {
        Object _ret = this.riInvokeExportedMethod(this,"vo_printCurrentVOQueryMode",null,null);
        return;
    }

    public void vo_executeQueryVOViewRows() {
        Object _ret = this.riInvokeExportedMethod(this,"vo_executeQueryVOViewRows",null,null);
        return;
    }

    public void vo_executeQueryVOEntityObjects() {
        Object _ret = this.riInvokeExportedMethod(this,"vo_executeQueryVOEntityObjects",null,null);
        return;
    }

    public void vo_executeQueryVODBTables() {
        Object _ret = this.riInvokeExportedMethod(this,"vo_executeQueryVODBTables",null,null);
        return;
    }

    public void so_printCurrentVOQueryMode() {
        Object _ret = this.riInvokeExportedMethod(this,"so_printCurrentVOQueryMode",null,null);
        return;
    }

    public void eo_printCurrentVOQueryMode() {
        Object _ret = this.riInvokeExportedMethod(this,"eo_printCurrentVOQueryMode",null,null);
        return;
    }
}
