
CREATE TABLE EMPLOYEES_HIST(
EMPLOYEE_ID   NUMBER(6,0) NOT NULL ENABLE,
LAST_NAME     VARCHAR2(25 BYTE) NOT NULL ENABLE,
DEPARTMENT_ID NUMBER(4, 0) NOT NULL,
VERSION_START BINARY_DOUBLE DEFAULT 0 NOT NULL ENABLE,
VERSION_END   BINARY_DOUBLE DEFAULT 0 NOT NULL ENABLE,
LAST_CHANGE_DATE TIMESTAMP DEFAULT (systimestamp) NOT NULL,
LAST_CHANGE_USER VARCHAR2(25 BYTE) NOT NULL,
CONSTRAINT EMPLOYEES_HIST_PK PRIMARY KEY (EMPLOYEE_ID, VERSION_END),
CONSTRAINT EMPLOYEES_HIST_DEPARTME_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

/

CREATE TABLE JOBS_HIST(
JOB_ID        VARCHAR2(10 BYTE) NOT NULL ENABLE,
JOB_TITLE     VARCHAR2(35 BYTE) NOT NULL ENABLE,
VERSION_START BINARY_DOUBLE DEFAULT 0 NOT NULL ENABLE,
VERSION_END   BINARY_DOUBLE DEFAULT 0 NOT NULL ENABLE,
LAST_CHANGE_DATE TIMESTAMP DEFAULT (systimestamp) NOT NULL,
LAST_CHANGE_USER VARCHAR2(25 BYTE) NOT NULL,
CONSTRAINT JOBS_HIST_PK PRIMARY KEY (JOB_ID, VERSION_END),
CONSTRAINT JOBS_HIST_DEPARTME_FK1 FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID)
);

/

CREATE TABLE DEPARTMENTS_HIST(
DEPARTMENT_ID   NUMBER(4,0) NOT NULL ENABLE,
DEPARTMENT_NAME VARCHAR2(30 BYTE) NOT NULL ENABLE,
VERSION_START   BINARY_DOUBLE DEFAULT 0 NOT NULL ENABLE,
VERSION_END     BINARY_DOUBLE DEFAULT 0 NOT NULL ENABLE,
LAST_CHANGE_DATE TIMESTAMP DEFAULT (systimestamp) NOT NULL,
LAST_CHANGE_USER VARCHAR2(25 BYTE) NOT NULL,
CONSTRAINT DEPARTMENTS_HIST_PK PRIMARY KEY (DEPARTMENT_ID, VERSION_END),
CONSTRAINT DEPARTMENTS_HIST_DEPARTME_FK1 FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

/

ALTER TABLE EMPLOYEES ADD (LAST_CHANGE_DATE TIMESTAMP DEFAULT (systimestamp) NOT NULL);
ALTER TABLE EMPLOYEES ADD (LAST_CHANGE_USER VARCHAR2(25 BYTE) DEFAULT ('user') NOT NULL );

ALTER TABLE JOBS ADD (LAST_CHANGE_DATE DATE TIMESTAMP DEFAULT (systimestamp) NOT NULL);
ALTER TABLE JOBS ADD (LAST_CHANGE_USER VARCHAR2(25 BYTE) DEFAULT ('user') NOT NULL );

ALTER TABLE DEPARTMENTS ADD (LAST_CHANGE_DATE TIMESTAMP DEFAULT (systimestamp) NOT NULL);
ALTER TABLE DEPARTMENTS ADD (LAST_CHANGE_USER VARCHAR2(25 BYTE) DEFAULT ('user') NOT NULL );

/


CREATE INDEX DEPARTMENTS_HIST_DN ON DEPARTMENTS_HIST (DEPARTMENT_NAME);
CREATE INDEX DEPARTMENTS_HIST_VS ON DEPARTMENTS_HIST (VERSION_START);
CREATE INDEX DEPARTMENTS_HIST_VE ON DEPARTMENTS_HIST (VERSION_END);
CREATE INDEX DEPARTMENTS_HIST_VSE ON DEPARTMENTS_HIST (VERSION_START,VERSION_END);
CREATE INDEX DEPARTMENTS_HIST_DI ON DEPARTMENTS_HIST (DEPARTMENT_ID);
CREATE INDEX DEPARTMENTS_HIST_LCD ON DEPARTMENTS_HIST (LAST_CHANGE_DATE);
CREATE INDEX DEPARTMENTS_LCD ON DEPARTMENTS (LAST_CHANGE_DATE);

CREATE INDEX EMPLOYEES_HIST_LN ON EMPLOYEES_HIST (LAST_NAME);
CREATE INDEX EMPLOYEES_HIST_DI ON EMPLOYEES_HIST (DEPARTMENT_ID);
CREATE INDEX EMPLOYEES_HIST_VS ON EMPLOYEES_HIST (VERSION_START);
CREATE INDEX EMPLOYEES_HIST_VE ON EMPLOYEES_HIST (VERSION_END);
CREATE INDEX EMPLOYEES_HIST_VSE ON EMPLOYEES_HIST (VERSION_START,VERSION_END);
CREATE INDEX EMPLOYEES_HIST_EI ON EMPLOYEES_HIST (EMPLOYEE_ID);
CREATE INDEX EMPLOYEES_HIST_LCD ON EMPLOYEES_HIST (LAST_CHANGE_DATE);
CREATE INDEX EMPLOYEES_LCD ON EMPLOYEES (LAST_CHANGE_DATE);

CREATE INDEX JOBS_HIST_JT ON JOBS_HIST (JOB_TITLE);
CREATE INDEX JOBS_HIST_VS ON JOBS_HIST (VERSION_START);
CREATE INDEX JOBS_HIST_VE ON JOBS_HIST (VERSION_END);
CREATE INDEX JOBS_HIST_VSE ON JOBS_HIST (VERSION_START, VERSION_END);
CREATE INDEX JOBS_HIST_JI ON JOBS_HIST (JOB_ID);
CREATE INDEX JOBS_HIST_LCD ON JOBS_HIST (LAST_CHANGE_DATE);
CREATE INDEX JOBS_LCD ON JOBS (LAST_CHANGE_DATE);

/