package com.virtual7.updateForHistorysation.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 24 17:19:22 EEST 2013
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void clearEntityCache();
}
