package com.virtual7.taskflowEndPoint.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 23 16:09:47 EEST 2012
// ---------------------------------------------------------------------
public interface TaskflowEndPointAppModule extends ApplicationModule {
    void doSomething();

    void doSomeOtherThing();
}
