package com.virtual7.xdm.model.entities;

import com.virtual7.xdm.framework.EntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 13:22:14 EET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XdmTasksImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TaskId {
            public Object get(XdmTasksImpl obj) {
                return obj.getTaskId();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setTaskId((DBSequence)value);
            }
        }
        ,
        ElemKey {
            public Object get(XdmTasksImpl obj) {
                return obj.getElemKey();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setElemKey((String)value);
            }
        }
        ,
        ProgId {
            public Object get(XdmTasksImpl obj) {
                return obj.getProgId();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setProgId((Number)value);
            }
        }
        ,
        StartDate {
            public Object get(XdmTasksImpl obj) {
                return obj.getStartDate();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        StartWhere {
            public Object get(XdmTasksImpl obj) {
                return obj.getStartWhere();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setStartWhere((String)value);
            }
        }
        ,
        Text {
            public Object get(XdmTasksImpl obj) {
                return obj.getText();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setText((String)value);
            }
        }
        ,
        EndDate {
            public Object get(XdmTasksImpl obj) {
                return obj.getEndDate();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        EndWhere {
            public Object get(XdmTasksImpl obj) {
                return obj.getEndWhere();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setEndWhere((String)value);
            }
        }
        ,
        Pax {
            public Object get(XdmTasksImpl obj) {
                return obj.getPax();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setPax((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(XdmTasksImpl obj) {
                return obj.getRemarks();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        FlightNo {
            public Object get(XdmTasksImpl obj) {
                return obj.getFlightNo();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setFlightNo((String)value);
            }
        }
        ,
        PersId {
            public Object get(XdmTasksImpl obj) {
                return obj.getPersId();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setPersId((Number)value);
            }
        }
        ,
        CxlYn {
            public Object get(XdmTasksImpl obj) {
                return obj.getCxlYn();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setCxlYn((String)value);
            }
        }
        ,
        XdmElements {
            public Object get(XdmTasksImpl obj) {
                return obj.getXdmElements();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setXdmElements((EntityImpl)value);
            }
        }
        ,
        XdmPersons {
            public Object get(XdmTasksImpl obj) {
                return obj.getXdmPersons();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setXdmPersons((EntityImpl)value);
            }
        }
        ,
        XdmProgrammes {
            public Object get(XdmTasksImpl obj) {
                return obj.getXdmProgrammes();
            }

            public void put(XdmTasksImpl obj, Object value) {
                obj.setXdmProgrammes((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(XdmTasksImpl object);

        public abstract void put(XdmTasksImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int ELEMKEY = AttributesEnum.ElemKey.index();
    public static final int PROGID = AttributesEnum.ProgId.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int STARTWHERE = AttributesEnum.StartWhere.index();
    public static final int TEXT = AttributesEnum.Text.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ENDWHERE = AttributesEnum.EndWhere.index();
    public static final int PAX = AttributesEnum.Pax.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int FLIGHTNO = AttributesEnum.FlightNo.index();
    public static final int PERSID = AttributesEnum.PersId.index();
    public static final int CXLYN = AttributesEnum.CxlYn.index();
    public static final int XDMELEMENTS = AttributesEnum.XdmElements.index();
    public static final int XDMPERSONS = AttributesEnum.XdmPersons.index();
    public static final int XDMPROGRAMMES = AttributesEnum.XdmProgrammes.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XdmTasksImpl() {
    }

    /**
     * Gets the attribute value for TaskId, using the alias name TaskId.
     * @return the TaskId
     */
    public DBSequence getTaskId() {
        return (DBSequence)getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaskId.
     * @param value value to set the TaskId
     */
    public void setTaskId(DBSequence value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for ElemKey, using the alias name ElemKey.
     * @return the ElemKey
     */
    public String getElemKey() {
        return (String)getAttributeInternal(ELEMKEY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ElemKey.
     * @param value value to set the ElemKey
     */
    public void setElemKey(String value) {
        setAttributeInternal(ELEMKEY, value);
    }

    /**
     * Gets the attribute value for ProgId, using the alias name ProgId.
     * @return the ProgId
     */
    public Number getProgId() {
        return (Number)getAttributeInternal(PROGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProgId.
     * @param value value to set the ProgId
     */
    public void setProgId(Number value) {
        setAttributeInternal(PROGID, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for StartWhere, using the alias name StartWhere.
     * @return the StartWhere
     */
    public String getStartWhere() {
        return (String)getAttributeInternal(STARTWHERE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartWhere.
     * @param value value to set the StartWhere
     */
    public void setStartWhere(String value) {
        setAttributeInternal(STARTWHERE, value);
    }

    /**
     * Gets the attribute value for Text, using the alias name Text.
     * @return the Text
     */
    public String getText() {
        return (String)getAttributeInternal(TEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Text.
     * @param value value to set the Text
     */
    public void setText(String value) {
        setAttributeInternal(TEXT, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for EndWhere, using the alias name EndWhere.
     * @return the EndWhere
     */
    public String getEndWhere() {
        return (String)getAttributeInternal(ENDWHERE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndWhere.
     * @param value value to set the EndWhere
     */
    public void setEndWhere(String value) {
        setAttributeInternal(ENDWHERE, value);
    }

    /**
     * Gets the attribute value for Pax, using the alias name Pax.
     * @return the Pax
     */
    public Number getPax() {
        return (Number)getAttributeInternal(PAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pax.
     * @param value value to set the Pax
     */
    public void setPax(Number value) {
        setAttributeInternal(PAX, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for FlightNo, using the alias name FlightNo.
     * @return the FlightNo
     */
    public String getFlightNo() {
        return (String)getAttributeInternal(FLIGHTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlightNo.
     * @param value value to set the FlightNo
     */
    public void setFlightNo(String value) {
        setAttributeInternal(FLIGHTNO, value);
    }

    /**
     * Gets the attribute value for PersId, using the alias name PersId.
     * @return the PersId
     */
    public Number getPersId() {
        return (Number)getAttributeInternal(PERSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersId.
     * @param value value to set the PersId
     */
    public void setPersId(Number value) {
        setAttributeInternal(PERSID, value);
    }

    /**
     * Gets the attribute value for CxlYn, using the alias name CxlYn.
     * @return the CxlYn
     */
    public String getCxlYn() {
        return (String)getAttributeInternal(CXLYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for CxlYn.
     * @param value value to set the CxlYn
     */
    public void setCxlYn(String value) {
        setAttributeInternal(CXLYN, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity com.virtual7.xdm.framework.EntityImpl.
     */
    public EntityImpl getXdmElements() {
        return (EntityImpl)getAttributeInternal(XDMELEMENTS);
    }

    /**
     * Sets <code>value</code> as the associated entity com.virtual7.xdm.framework.EntityImpl.
     */
    public void setXdmElements(EntityImpl value) {
        setAttributeInternal(XDMELEMENTS, value);
    }

    /**
     * @return the associated entity com.virtual7.xdm.framework.EntityImpl.
     */
    public EntityImpl getXdmPersons() {
        return (EntityImpl)getAttributeInternal(XDMPERSONS);
    }

    /**
     * Sets <code>value</code> as the associated entity com.virtual7.xdm.framework.EntityImpl.
     */
    public void setXdmPersons(EntityImpl value) {
        setAttributeInternal(XDMPERSONS, value);
    }

    /**
     * @return the associated entity com.virtual7.xdm.framework.EntityImpl.
     */
    public EntityImpl getXdmProgrammes() {
        return (EntityImpl)getAttributeInternal(XDMPROGRAMMES);
    }

    /**
     * Sets <code>value</code> as the associated entity com.virtual7.xdm.framework.EntityImpl.
     */
    public void setXdmProgrammes(EntityImpl value) {
        setAttributeInternal(XDMPROGRAMMES, value);
    }

    /**
     * @param taskId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence taskId) {
        return new Key(new Object[]{taskId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.virtual7.xdm.model.entities.XdmTasks");
        }
        return mDefinitionObject;
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        // set cancel flag. doDML() will change DELETE to UPDATE
        setCxlYn("Y");
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_DELETE) {
        super.doDML(DML_UPDATE, e);
        } else {
        super.doDML(operation, e);
        }
    }
}
