package com.virtual7.adfDevelopmentPattern.model.common;

import com.virtual7.util.model.context.AChangeContext;
import com.virtual7.util.model.context.AFilterContext;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 05 13:53:12 EET 2012
// ---------------------------------------------------------------------
public interface ADFPatternAM extends ApplicationModule {
    void filterDataModel(AFilterContext filterContext);

    void changeDataModel(AChangeContext changeContext, AFilterContext filterContext);
}
