package com.virtual7.updateForHistorysation.model.client;

import com.virtual7.updateForHistorysation.model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 24 17:19:22 EEST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void clearEntityCache() {
        Object _ret =
            this.riInvokeExportedMethod(this,"clearEntityCache",null,null);
        return;
    }
}
