package com.virtual7.amComplexParams.model.client;

import com.virtual7.amComplexParams.model.UserBean;
import com.virtual7.amComplexParams.model.UserList;
import com.virtual7.amComplexParams.model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 22 19:27:44 EEST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void saveUsers1(UserList userList) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveUsers1",new String [] {"com.virtual7.amComplexParams.model.UserList"},new Object[] {userList});
        return;
    }

    public void saveUsers(java.util.List<UserBean> users) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveUsers",new String [] {"java.util.List<com.virtual7.amComplexParams.model.UserBean>"},new Object[] {users});
        return;
    }
}
