package com.virtual7.historizationConcept.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 17:38:16 EEST 2011
// ---------------------------------------------------------------------
public interface UserView extends ViewObject {
    void filterByLastName(String value, String[] hiddenUserNrs);
}
