package model.views.client;

import model.views.common.EmployeestoaptitudeView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 17:18:34 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeestoaptitudeViewClient extends ViewUsageImpl implements EmployeestoaptitudeView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeestoaptitudeViewClient() {
    }

    public void createInsert(Number empId, Number aptId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createInsert",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {empId, aptId});
        return;
    }
}
