package com.virtual7.adfDevelopmentPattern.model;

import com.virtual7.adfDevelopmentPattern.model.common.ADFPatternAM;

import com.virtual7.util.model.BaseAppModuleImpl;

import com.virtual7.util.model.operations.AOperationFactory;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 05 13:53:12 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ADFPatternAMImpl extends BaseAppModuleImpl implements ADFPatternAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ADFPatternAMImpl() {
    }

    /**
     * Container's getter for DepartmentsLOV.
     * @return DepartmentsLOV
     */
    public ViewObjectImpl getDepartmentsLOV() {
        return (ViewObjectImpl)findViewObject("DepartmentsLOV");
    }

    /**
     * Container's getter for EmployeesTable.
     * @return EmployeesTable
     */
    public ViewObjectImpl getEmployeesTable() {
        return (ViewObjectImpl)findViewObject("EmployeesTable");
    }

    protected AOperationFactory getOperationFactory() {
        return ADFPatternOperationFactory.getInstance();
    }
}
