package com.virtual7.bcCachingService.model.common.serviceinterface;

import com.virtual7.bcCachingService.model.views.common.DepartmentServiceVOSDO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 15:44:16 EEST 2012
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/com/virtual7/bcCachingService/model/common/", name="AppModuleService",
    wsdlLocation="com/virtual7/bcCachingService/model/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation="com/virtual7/bcCachingService/model/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/com/virtual7/bcCachingService/model/common/}AppModuleService";

    @WebMethod(action="/com/virtual7/bcCachingService/model/common/createDepartmentServiceVO", operationName="createDepartmentServiceVO")
    @RequestWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="createDepartmentServiceVO")
    @ResponseWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="createDepartmentServiceVOResponse")
    @WebResult(name="result")
    DepartmentServiceVOSDO createDepartmentServiceVO(@WebParam(mode = WebParam.Mode.IN, name="departmentServiceVO")
        DepartmentServiceVOSDO departmentServiceVO) throws ServiceException;

    @WebMethod(action="/com/virtual7/bcCachingService/model/common/updateDepartmentServiceVO", operationName="updateDepartmentServiceVO")
    @RequestWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="updateDepartmentServiceVO")
    @ResponseWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="updateDepartmentServiceVOResponse")
    @WebResult(name="result")
    DepartmentServiceVOSDO updateDepartmentServiceVO(@WebParam(mode = WebParam.Mode.IN, name="departmentServiceVO")
        DepartmentServiceVOSDO departmentServiceVO) throws ServiceException;

    @WebMethod(action="/com/virtual7/bcCachingService/model/common/deleteDepartmentServiceVO", operationName="deleteDepartmentServiceVO")
    @RequestWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="deleteDepartmentServiceVO")
    @ResponseWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="deleteDepartmentServiceVOResponse")
    void deleteDepartmentServiceVO(@WebParam(mode = WebParam.Mode.IN, name="departmentServiceVO")
        DepartmentServiceVOSDO departmentServiceVO) throws ServiceException;

    @WebMethod(action="/com/virtual7/bcCachingService/model/common/mergeDepartmentServiceVO", operationName="mergeDepartmentServiceVO")
    @RequestWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="mergeDepartmentServiceVO")
    @ResponseWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="mergeDepartmentServiceVOResponse")
    @WebResult(name="result")
    DepartmentServiceVOSDO mergeDepartmentServiceVO(@WebParam(mode = WebParam.Mode.IN, name="departmentServiceVO")
        DepartmentServiceVOSDO departmentServiceVO) throws ServiceException;

    @WebMethod(action="/com/virtual7/bcCachingService/model/common/findDepartmentServiceVO", operationName="findDepartmentServiceVO")
    @RequestWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="findDepartmentServiceVO")
    @ResponseWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="findDepartmentServiceVOResponse")
    @WebResult(name="result")
    List<DepartmentServiceVOSDO> findDepartmentServiceVO(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/com/virtual7/bcCachingService/model/common/processDepartmentServiceVO", operationName="processDepartmentServiceVO")
    @RequestWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="processDepartmentServiceVO")
    @ResponseWrapper(targetNamespace="/com/virtual7/bcCachingService/model/common/types/", localName="processDepartmentServiceVOResponse")
    @WebResult(name="result")
    List<DepartmentServiceVOSDO> processDepartmentServiceVO(@WebParam(mode = WebParam.Mode.IN, name="changeOperation")
        String changeOperation, @WebParam(mode = WebParam.Mode.IN, name="departmentServiceVO")
        List<DepartmentServiceVOSDO> departmentServiceVO, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;
}
