package com.virtual7.programaticPivotTableBinding.model.views.client;

import com.virtual7.programaticPivotTableBinding.model.views.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 07 18:15:10 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void changeDynamicQuerry(String querry) {
        Object _ret = this.riInvokeExportedMethod(this,"changeDynamicQuerry",new String [] {"java.lang.String"},new Object[] {querry});
        return;
    }
}
