package com.virtual7.multipleFileUpload.model.server.serviceinterface;

import com.virtual7.multipleFileUpload.model.common.serviceinterface.AppModuleService;
import com.virtual7.multipleFileUpload.model.views.common.EmployeesViewSDO;

import java.lang.reflect.Method;

import java.util.List;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 17:01:35 EET 2011
// ---------------------------------------------------------------------
@Stateless(name = "com.virtual7.multipleFileUpload.model.common.AppModuleServiceBean",
           mappedName = "AppModuleServiceBean")
@Remote(AppModuleService.class)
@PortableWebService(targetNamespace = "/com/virtual7/multipleFileUpload/model/common/",
                    serviceName = "AppModuleService", portName = "AppModuleServiceSoapHttpPort",
                    endpointInterface = "com.virtual7.multipleFileUpload.model.common.serviceinterface.AppModuleService")
@Interceptors( { ServiceContextInterceptor.class })
public class AppModuleServiceImpl extends ServiceImpl implements AppModuleService {
    private static boolean _isInited = false;

    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleServiceImpl() {
        init();
        setApplicationModuleDefName("com.virtual7.multipleFileUpload.model.AppModule");
        setConfigurationName("AppModuleService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (AppModuleServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("com/virtual7/multipleFileUpload/model/common/serviceinterface/",
                                                "AppModuleService.xsd");
                _isInited = true;
            } catch (Exception ex) {
                Diagnostic.printStackTrace(ex);
            }
        }
    }

    /**
     * findEmployeesView1: generated method. Do not modify.
     */
    public List<EmployeesViewSDO> findEmployeesView1(FindCriteria findCriteria,
                                                     FindControl findControl) throws ServiceException {
        return (List<EmployeesViewSDO>)find(findCriteria, findControl, "EmployeesView1", EmployeesViewSDO.class);
    }
}
