package com.virtual7.multipleFileUpload.model.common.serviceinterface;

import com.virtual7.multipleFileUpload.model.views.common.EmployeesViewSDO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 17:01:35 EET 2011
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/com/virtual7/multipleFileUpload/model/common/", name = "AppModuleService",
                    wsdlLocation =
                    "com/virtual7/multipleFileUpload/model/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation = "com/virtual7/multipleFileUpload/model/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/com/virtual7/multipleFileUpload/model/common/}AppModuleService";

    @WebMethod(action = "/com/virtual7/multipleFileUpload/model/common/findEmployeesView1",
               operationName = "findEmployeesView1")
    @RequestWrapper(targetNamespace = "/com/virtual7/multipleFileUpload/model/common/types/",
                    localName = "findEmployeesView1")
    @ResponseWrapper(targetNamespace = "/com/virtual7/multipleFileUpload/model/common/types/",
                     localName = "findEmployeesView1Response")
    @WebResult(name = "result")
    List<EmployeesViewSDO> findEmployeesView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name = "findControl")
        FindControl findControl) throws ServiceException;
}
