DROP TABLE APTITUDE
DROP TABLE EMPLOYEESTOAPTITUDE

CREATE TABLE APTITUDE
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE TABLE EMPLOYEESTOAPTITUDE
   (	"ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER(3,0), 
	"APTITUDE_ID" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


CREATE SEQUENCE  "HR"."APTITUDE_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "HR"."EMPTOAPTSEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE;



ALTER TABLE "HR"."APTITUDE" ADD CONSTRAINT "APTITUDE_PK" PRIMARY KEY ("ID");
ALTER TABLE "HR"."APTITUDE" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "HR"."EMPLOYEESTOAPTITUDE" ADD CONSTRAINT "EMPLOYEESTOAPTITUDE_PK" PRIMARY KEY ("ID");
ALTER TABLE "HR"."EMPLOYEESTOAPTITUDE" MODIFY ("ID" NOT NULL ENABLE);
