DROP TABLE APTITUDE;
DROP TABLE EMPLOYEESTOAPTITUDE;

CREATE TABLE APTITUDE
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   );


CREATE TABLE EMPLOYEESTOAPTITUDE
   (	"ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER(3,0), 
	"APTITUDE_ID" NUMBER(3,0)
   );


CREATE SEQUENCE  APTITUDE_SEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  EMPTOAPTSEQ  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE;


ALTER TABLE APTITUDE ADD CONSTRAINT "APTITUDE_PK" PRIMARY KEY ("ID");
ALTER TABLE APTITUDE MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE EMPLOYEESTOAPTITUDE ADD CONSTRAINT "EMPLOYEESTOAPTITUDE_PK" PRIMARY KEY ("ID");
ALTER TABLE EMPLOYEESTOAPTITUDE MODIFY ("ID" NOT NULL ENABLE);
