SPOOL 003_create_objects.log

DROP TABLE UTILS_CONFIG CASCADE CONSTRAINTS;

DROP TABLE CONFIG CASCADE CONSTRAINTS;

CREATE TABLE UTILS_CONFIG 
(
  ID NUMBER(10, 0) NOT NULL 
, CONFIG_KEY VARCHAR2(255 CHAR) NOT NULL 
, CONFIG_VALUE VARCHAR2(2048 CHAR) 
, CONSTRAINT UTILS_CONFIG_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE CONFIG 
(
  ID NUMBER(10, 0) NOT NULL 
, CONFIG_KEY VARCHAR2(255 CHAR) NOT NULL 
, CONFIG_VALUE VARCHAR2(2048 CHAR) 
, CONSTRAINT CONFIG_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN UTILS_CONFIG.ID IS 'primary key';

COMMENT ON COLUMN UTILS_CONFIG.CONFIG_KEY IS 'configuration key name';

COMMENT ON COLUMN UTILS_CONFIG.CONFIG_VALUE IS 'configuration value';

COMMENT ON COLUMN CONFIG.CONFIG_KEY IS 'configuration key name';

COMMENT ON COLUMN CONFIG.CONFIG_VALUE IS 'configuration value';

SPOOL OFF