package com.virtual7.amComplexParams.model.common;

import com.virtual7.amComplexParams.model.UserBean;
import com.virtual7.amComplexParams.model.UserList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 22 19:27:44 EEST 2013
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void saveUsers1(UserList userList);

    void saveUsers(java.util.List<UserBean> users);
}
