package com.virtual7.businessComponents.model;

import com.virtual7.businessComponents.model.common.AppModule;
import com.virtual7.businessComponents.model.views.EmployeesWithCriteriasViewImpl;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaManager;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 15 12:08:38 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl)findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for EmployeesWithCriteriasView1.
     * @return EmployeesWithCriteriasView1
     */
    public ViewObjectImpl getEmployeesWithCriteriasView() {
        return (ViewObjectImpl)findViewObject("EmployeesWithCriteriasView");
    }

    public void varEmail() {

        EmployeesWithCriteriasViewImpl employees = (EmployeesWithCriteriasViewImpl) getEmployeesWithCriteriasView();
        ViewCriteriaManager vcm = employees.getViewCriteriaManager();
        ViewCriteria emailVC = vcm.getViewCriteria("EmailVC");
        VariableValueManager vvm = emailVC.ensureVariableManager();
        vvm.setVariableValue("EmailVar", "DFAVIET");
        employees.setApplyViewCriteriaName("EmailVC");
        
        employees.clearCache();
    }

    public void varSalary() {    
        
        EmployeesWithCriteriasViewImpl employees = (EmployeesWithCriteriasViewImpl) getEmployeesWithCriteriasView();
        ViewCriteriaManager vcm = employees.getViewCriteriaManager();
        ViewCriteria emailVC = vcm.getViewCriteria("SalaryVC");
        VariableValueManager vvm = emailVC.ensureVariableManager();
        vvm.setVariableValue("SalaryVar", 10000);
        employees.setApplyViewCriteriaName("SalaryVC");
        
        employees.clearCache();
    }

    public void varLName() {
        
        EmployeesWithCriteriasViewImpl employees = (EmployeesWithCriteriasViewImpl) getEmployeesWithCriteriasView();
        ViewCriteriaManager vcm = employees.getViewCriteriaManager();
        ViewCriteria emailVC = vcm.getViewCriteria("NameVC");
        VariableValueManager vvm = emailVC.ensureVariableManager();
        vvm.setVariableValue("LName", "King");
        employees.setApplyViewCriteriaName("NameVC");
        
        employees.clearCache();
    
    }

    public void varFName() {
        
    }
    
    public void removeWhereClauseParam() {
        ViewObjectImpl employees = getEmployeesWithCriteriasView();
        ViewCriteriaManager vcm = employees.getViewCriteriaManager();
        vcm.removeApplyViewCriteriaName("NameVC");
        vcm.removeApplyViewCriteriaName("SalaryVC");
        vcm.removeApplyViewCriteriaName("EmailVC");
        
        employees.clearCache();
    }

    /**
     * Container's getter for EmployeesView.
     * @return EmployeesView
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl)findViewObject("EmployeesView1");
    }


    /**
     * Container's getter for EmpHierarchy1.
     * @return EmpHierarchy1
     */
    public ViewObjectImpl getEmpHierarchy1() {
        return (ViewObjectImpl)findViewObject("EmpHierarchy1");
    }


}
