package com.virtual7.bcCaching.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 16:06:01 EEST 2012
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void updateDepartmentNewJDBC();

    void updateDepartment();

    void readAndPrintDepartmentService();

    void readAndPrintDepartmentNewJDBC();

    void readAndPrintDepartment();

    void insertNewDepartmentNewJDBC();

    void insertNewDepartment();

    void executeServiceQueryVL();

    void executeServiceQueryEL();

    void executeServiceQuery();

    void executeQuery6();

    void executeQuery5();

    void executeQuery4();

    void executeQuery3();

    void executeQuery2();

    void executeQuery1();

    void executeQuery();

    void deleteDepartmentNewJDBC();

    void deleteDepartment();
}
