package com.virtual7.bcCaching.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 16:06:01 EEST 2012
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void updateDepartmentNewJDBC();

    void updateDepartment();


    void readAndPrintDepartmentNewJDBC();

    void readAndPrintDepartment();

    void insertNewDepartmentNewJDBC();

    void insertNewDepartment();


    void deleteDepartmentNewJDBC();

    void deleteDepartment();

    void vo_printCurrentVOQueryMode();

    void vo_executeQueryVOViewRows();

    void vo_executeQueryVOEntityObjects();

    void vo_executeQueryVODBTables();

    void so_printCurrentVOQueryMode();

    void eo_printCurrentVOQueryMode();

    void so_executeQuerySOVOViewRows();

    void so_executeQuerySOVOEntityObject();

    void so_executeQuerySOVODBTables();

    void eo_executeQueryEOVOViewRows();

    void eo_executeQueryEOVOEntityObject();

    void eo_executeQueryEOVODBTables();

    void so_readAndPrintDepartmentService();

    void postChangesAction();

    void so_cleareEntityCache();

    void so_clearViewObjectCache();

    void eo_cleareEntityCache();

    void eo_clearViewObjectCache();

    void vo_clearViewObjectCache();
}
