package model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 16:11:49 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AptitudeViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AptitudeViewImpl() {
    }
}
