package model.views;


import model.views.common.EmployeestoaptitudeView;

import oracle.jbo.NameValuePairs;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 17:16:26 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeestoaptitudeViewImpl extends ViewObjectImpl implements EmployeestoaptitudeView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeestoaptitudeViewImpl() {
    }
    
    public void createInsert(oracle.jbo.domain.Number empId, oracle.jbo.domain.Number aptId) {
           NameValuePairs nvp = new NameValuePairs();
           nvp.setAttribute("EmployeeId", empId);
           nvp.setAttribute("Aptitudeid", aptId);
           EmployeestoaptitudeViewRowImpl newRow = (EmployeestoaptitudeViewRowImpl) this.createAndInitRow(nvp);
//           this.executeQuery();
           this.getDefaultRowSet().insertRow(newRow);
           //this.getApplicationModule().getTransaction().commit();
       }
}
