package com.virtual7.historizationConcept.model.views;


import com.virtual7.historizationConcept.model.views.common.UserView;



import java.sql.ResultSet;

import oracle.jbo.domain.Array;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 26 16:11:16 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserViewImpl extends com.virtual7.util.model.views.UserViewImpl implements UserView {

    /**
     * This is the default constructor (do not remove).
     */
    public UserViewImpl() {
    }


    /**
     * Sets <code>value</code> for bind variable lastNameFilterVar.
     *
     * @param value value to bind as lastNameFilterVar
     */
    public void filterByLastName(String value, String[] hiddenUserNrs) {
        if (value == null) {
            value = "";
        }
        this.setgetRoles(false);
        this.setqueryType(LAST_NAME_QUERY);
        this.setsearchFilter(value);

        Array hiddenUserNrsArr = new Array(new String[0]);
        if (hiddenUserNrs != null) {
            hiddenUserNrsArr = new Array(hiddenUserNrs);
        }
        this.sethiddenUserNr(hiddenUserNrsArr);
        this.executeQuery();
    }


    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc, ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
}
