package com.virtual7.historizationConcept.model.views;



import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 09 14:02:16 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserViewRowImpl extends com.virtual7.util.model.views.UserViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserViewRowImpl() {
    }
}
