DROP SEQUENCE MESSAGES_SEQ;

DROP TABLE MESSAGES;

CREATE TABLE MESSAGES 
(
  ID NUMBER NOT NULL 
, CONTENT VARCHAR2(200 BYTE) 
, CONSTRAINT MESSAGES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE MESSAGES_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER MESSAGES_TRG BEFORE INSERT ON MESSAGES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL OR :NEW.ID<0
  THEN
    SELECT MESSAGES_SEQ.NEXTVAL into :NEW.ID FROM DUAL;
  END IF;
END;
/
