package com.virtual7.businessComponents.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 15 13:06:28 EEST 2012
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void varSalary();

    void varLName();

    void varFName();

    void varEmail();

    void removeWhereClauseParam();
}
