package com.virtual7.adfDevelopmentPattern.model.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 05 14:40:19 EET 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOImpl() {
    }

    /**
     * Returns the variable value for DeptIdVar.
     * @return variable value for DeptIdVar
     */
    public Number getDeptIdVar() {
        return (Number)ensureVariableManager().getVariableValue("DeptIdVar");
    }

    /**
     * Sets <code>value</code> for variable DeptIdVar.
     * @param value value to bind as DeptIdVar
     */
    public void setDeptIdVar(Number value) {
        ensureVariableManager().setVariableValue("DeptIdVar", value);
    }
}
