DROP TABLE PRICE_PER_YEAR CASCADE CONSTRAINTS;

DROP TABLE PRICE_PER_MONTH CASCADE CONSTRAINTS;

CREATE TABLE PRICE_PER_YEAR 
(
  ID NUMBER(10, 0) NOT NULL 
, SYSTEM_ID NUMBER(10, 0)
, SYSTEM_NAME VARCHAR2(255 CHAR)
, YEAR NUMBER(4, 0) 
, PRICE NUMBER(10, 0) 
, CONSTRAINT PRICE_PER_YEAR_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PRICE_PER_MONTH 
(
  ID NUMBER(10, 0) NOT NULL 
, SYSTEM_ID NUMBER(10, 0)
, SYSTEM_NAME VARCHAR2(255 CHAR)
, YEAR NUMBER(4, 0) 
, MONTH NUMBER(2, 0)
, PRICE NUMBER(10, 0) 
, CONSTRAINT PRICE_PER_MONTH_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
