package com.virtual7.pdfGenerator.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 21 10:23:30 EEST 2012
// ---------------------------------------------------------------------
public interface EmployeesAppModule extends ApplicationModule {
    void generatePDF();
}
