package com.virtual7.taskflowEndPoint.model;

import com.virtual7.taskflowEndPoint.model.common.TaskflowEndPointAppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 23 16:08:53 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskflowEndPointAppModuleImpl extends ApplicationModuleImpl implements TaskflowEndPointAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public TaskflowEndPointAppModuleImpl() {
    }

    /**
     * Container's getter for EmployeesVO.
     * @return EmployeesVO
     */
    public ViewObjectImpl getEmployeesVO() {
        return (ViewObjectImpl)findViewObject("EmployeesVO");
    }
    
    public void doSomething() {
        System.out.println("Did something.");
    }
    
    public void doSomeOtherThing() {
        System.out.println("Did some other thing.");
    }
}
