package com.virtual7.taskflowEndPoint.model.client;

import com.virtual7.taskflowEndPoint.model.common.TaskflowEndPointAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 23 16:09:47 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskflowEndPointAppModuleClient extends ApplicationModuleImpl implements TaskflowEndPointAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public TaskflowEndPointAppModuleClient() {
    }

    public void doSomething() {
        Object _ret = this.riInvokeExportedMethod(this,"doSomething",null,null);
        return;
    }

    public void doSomeOtherThing() {
        Object _ret = this.riInvokeExportedMethod(this,"doSomeOtherThing",null,null);
        return;
    }
}
