package com.virtual7.exceptionHandler.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 07 18:27:29 EET 2011
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void methodThatGenerateException();
}
