package model.views.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 17:18:32 EEST 2012
// ---------------------------------------------------------------------
public interface EmployeestoaptitudeView extends ViewObject {
    void createInsert(Number empId, Number aptId);
}
