package com.virtual7.programaticPivotTableBinding.model.views.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 07 18:15:10 EEST 2012
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void changeDynamicQuerry(String querry);
}
